version: '3'
services:
  caddy:
    image: "abiosoft/caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ../../.caddy:/root/.caddy
  feathers:
    build: ../
    environment:
      - NODE_ENV
      - POSTGRES_CONNECTION
      - FASTMAIL_PASSWORD